pretraining:
  data_dir: "/path/to/tfrecords/"
  batch_size: 8 # the batch size is the number of training images you want to process before updating the model weights. 
  micro_batch_size: 8 # here a micro batch is the amount of training images you want to process simultaneously on the GPU. If your GPU memory is not large enough to process the full batch size, you can set this to a smaller number and the training loop will automatically accumulate gradients until it has processed the full batch size before updating the model weights. Note that the batch size must be divisible by the micro batch size.
  epochs: 1000
  lam_max: 100.0
  experiment_name: "name_of_model"
  loss_type: "huber"
  learning_rate: 0.0001
  out_dir: "/path/to/save/models/"
  resume: false
  make_plots: false 
  save_model: true # if false do not save the model -OR- any checkpoints (useful for hyperparameter tuning)