pretraining:
  data_dir: "/path/to/tfrecords/"
  batch_size: 1
  epochs: 1000
  experiment_name: "name_of_model"
  loss_type: "huber"
  learning_rate: 0.0001
  out_dir: "/path/to/save/models/"
  resume: false
  make_plots: false 
  save_model: true # if false do not save the model -OR- any checkpoints (useful for hyperparameter tuning)