name: Black

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Black
        run: pip install black

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **/*.py

      - name: Check formatting with Black
        if: steps.changed-files.outputs.any_changed == 'true'
        continue-on-error: true
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: black --check --diff $CHANGED_FILES
