# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package (Main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
            python-version: '<3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Install package
      run: pip install .
    - name: Run tests
      run: |
        pip install pytest
        python -c "import os; print(os.getcwd())"
        cd tests
        python -m pytest -W ignore::DeprecationWarning -p no:cacheprovider
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') # if a new tag is pushed
    runs-on: ubuntu-latest
    steps:
    - name: Publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.IGM_TOKEN }}
        repository-url: https://upload.pypi.org/legacy/
